export enum Localization {
  CATEGORIES = 'Categories',
  ALL_DOCUMENTS = 'All documents',
  CATEGORY_NAME = 'Category name',
  CANCEL = 'Cancel',
  CREATE = 'Create',
  CREATE_CATEGORY = 'Create category',
  SEE = 'See',
  RENAME_DOC = 'Rename doc',
  MOVE_DOC = 'Move doc',
  DELETE = 'Delete',
  SETTINGS = 'Settings',
  NEW_NAME = 'New name',
  RENAME = 'Rename',
  MAIN_FOLDER = 'Main folder',
  MOVE = 'Move',
  CHOOSE_CATEGORY = 'Choose a category',
}
